version: '3.7'
services:
  postgres:
    image: postgres:11.9
    ports:
      - '127.0.0.1:5432:5432'
    container_name: doctolib_retro_postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${USER}']
